### ISSUE TITLE
PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/wordpress/wp-content/plugins/authldap/src/Wrapper/Ldap.php on line 73

### ISSUE THREAD

**Issue by vnovakovic** [heiglandreas/authLdap#242]
Hi Andreas,

I'm trying to setup authLDAP correctly with AD under WordPress and user authentication works good, but the part with recognizing groups does not go well.

I'm getting the following warning if I setup Group-Base:

``` php
PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/wordpress/wp-content/plugins/authldap/src/Wrapper/Ldap.php on line 73, referer: http://dev.test.internal/wp-login.php
``` 

Here are configuration parameters of authLDAP in Wordpress:

General Usage of authLDAP
-
``` html
Enable Authentication via LDAP? (yes)
Debug AuthLDAP? (yes)
Do not authenticate existing WordPress-Users (empty/default)
Map LDAP Groups to wordpress Roles? (yes)
``` 

General Server Settings
-
```html 
LDAP URI: ldap://CN=ldapreadonly,CN=Users,DC=test,DC=internal:password@10.8.1.21/dc=test,dc=internal;ldap://CN=ldapreadonly,CN=Users,DC=test,DC=internal:password@10.8.1.22/dc=test,dc=internal
LDAP URI-Separator: ;
StartTLS: (empty/default)
Filter: (userPrincipalName=%s)
```
 
Settings for creating new Users
-
```html
User-Read: (yes)
Name-Attribute: (name/defaults)
Second Name Attribute: sn
User-ID Attribute: userPrincipalName
Mail Attribute: mail
Web-Attribute: (empty/default)
Default Role: (None (deny access))
``` 

Groups for Roles
-
```html 
LDAP Groups override role of existing users?: (yes)
Group-Base: cn=Users,dn=test,dn=internal (this is correct groups are in cn=Users in Windows AD created)
Group-Attribute: memberOf
Group-Separator: _
Group-Filter: (&(objectClass=user)(userPrincipalName=%s)(memberOf=*)) 
``` 

Role - group mapping
-
``` html
Assign this WordPress-Role	to members of this/these LDAP-Groups

Administrator: WP-ADMINISTRATORS-TEST
Editor: WP-EDITORS-TEST
Author:	WP-AUTHORS-TEST
Contributor: WP-CONTRIBUTORS-TEST
Subscriber: WP-SUBSCRIBERS-TEST
``` 

Wordpress: 6.3.1
PHP Version: 8.1.2

PHP LDAP:
LDAP Support	enabled
Total Links		0/unlimited
API Version		3001
Vendor Name		OpenLDAP
Vendor Version	20511
SASL Support	Enabled

Logs:

```php
[Fri Sep 15 10:47:57.061899 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] User 'testuser08@test.internal' logging in, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.061985 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] about to do LDAP authentication, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.062015 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] connect to LDAP server, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.064309 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] LDAP authentication successful, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.064869 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.064918 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.064953 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] Group Filter: "(&(objectClass=user)(sAMAccountName=%s)(memberOf=*))", referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.064991 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] Group Base: cn=Users,dn=test,dn=internal, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.065200 2023] [php:warn] [pid 36853] [client 10.8.1.82:49312] PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/wordpress/wp-content/plugins/authldap/src/Wrapper/Ldap.php on line 73, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.065250 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] Exception getting LDAP group attributes: Search for (&(objectClass=user)(userPrincipalName=testuser08@test.internal)(memberOf=*)) was not successfull, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 10:47:57.065288 2023] [php:notice] [pid 36853] [client 10.8.1.82:49312] [AuthLDAP] user is not in any group that is allowed access, referer: http://dev.test.internal/wp-login.php
``` 

Log with empty Group_base setup, there is no PHP warning, but still user as a part of the proper group can not be authorized. 

User: testuser08@test.internal is member of WP-EDITORS-TEST group, but in this case **_Roles from LDAP group: []_** are empty. With a comment that: **_user is not in any group that is allowed access_** but the system should know that EDITOR group is WP-EDITORS-TEST group! or? Something is still missing or not correct:-(

```php
[Fri Sep 15 12:23:42.359384 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] User 'testuser08@test.internal' logging in, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.359570 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] about to do LDAP authentication, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.359630 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] connect to LDAP server, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.361880 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] LDAP authentication successful, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362483 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362607 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362686 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] Group Filter: "(&(objectClass=user)(userPrincipalName=%s)(memberOf=*))", referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362746 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] Group Base: , referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.363101 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] LDAP groups: ["CN=WP-EDITORS-TEST,CN=Users,DC=test,DC=internal","CN=Group_1d4448da-e39f-41c9-855b-1b16f81d17c9,OU=o365,DC=test,DC=internal"], referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.363177 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] Roles from LDAP group: [], referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.363250 2023] [php:notice] [pid 37572] [client 10.201.1.178:57445] [AuthLDAP] user is not in any group that is allowed access, referer: http://dev.test.internal/wp-login.php
``` 

I hope that this information can help us to determinate where is the root cause.

Kind regards,
Vlad

**Comment by heiglandreas** [comment]
Thanks for this detailed report! 

Makes it easy to figure out what is going on :grin: 

For one thing: You have set the `Group-Attribute` to `memberOf`. The group attribute is the attribute that is used to determine the group(s) that you define further down in the config. So in your case it is the attribute of the group that holds the value `WP-EDITORS-TEST`. And that seems to be `cn` and not `memberOf`. So that should fix the second issue.

The other issue seems to be that you try to search for groups in a part of the LDAP-server that just doesn't exist.

Your settings for Group-Base are `cn=Users,dn=test,dn=internal`. But your LDAP-URI contains `dc=test,dc=internal` as the base-path. Note the difference between `dc=test` and `dn=test`.

Apart from that: You only need to set the Group-Base when you explicitly set the base-path to a path where only users are located but the groups can't be reached or when you have multiple groups with the same unique identifier attribute within different branches. So in your case you should be able to leave the Group-Base empty and be happy.

Hope that helps. If not, please do come back!

**Comment by vnovakovic** [comment]
Great, PHP warning gone... I was really blind no to catch this. Thank you for prompt answer. :-)

but, I still have issue with a query with following setup:

Group-Base: dc=eyodwa,dc=net
Group-Attribute: memberOf
-
Finding a group, but after it, could not determinate **Roles from LDAP group: []**
```php
[Fri Sep 15 12:23:42.359384 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] User 'testuser08@test.internal' logging in, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.359570 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] about to do LDAP authentication, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.359630 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] connect to LDAP server, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.361880 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] LDAP authentication successful, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362483 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362607 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362686 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] Group Filter: "(&(objectClass=user)(userPrincipalName=%s)(memberOf=*))", referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.362746 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] Group Base: , referer: http://dev.test.internal/wp-login.php
```
```typecript
[Fri Sep 15 12:23:42.363101 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] LDAP groups: ["CN=WP-EDITORS-PROD,CN=Users,DC=test,DC=internal","CN=Group_1c4448da-e39f-41c9-855b-1b16f81d17c9,OU=o365,DC=test,DC=internal"], referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 12:23:42.363177 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] Roles from LDAP group: [], referer: http://dev.test.internal/wp-login.php
```
```php
[Fri Sep 15 12:23:42.363250 2023] [php:notice] [pid 37572] [client 10.8.1.178:57445] [AuthLDAP] user is not in any group that is allowed access, referer: http://dev.test.internal/wp-login.php
```

Group-Base: dc=eyodwa,dc=net
Group-Attribute: cn
-
It is trying to search for group **LDAP groups: ["testuser08"]** that does not exist at all, it is a sAMAccountName.
```php
[Fri Sep 15 15:49:28.845865 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] User 'testuser08@test.internal' logging in, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.845938 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] about to do LDAP authentication, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.845966 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] connect to LDAP server, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.848025 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] LDAP authentication successful, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.848588 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.848649 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] Array\n(\n    [administrator] => WP-ADMINISTRATORS-TEST\n    [editor] => WP-EDITORS-TEST\n    [author] => WP-AUTHORS-TEST\n    [contributor] => WP-CONTRIBUTORS-TEST\n    [subscriber] => WP-SUBSCRIBERS-TEST\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.848683 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] Group Filter: "(&(objectClass=user)(userPrincipalName=%s)(cn=*))", referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.848706 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] Group Base: dc=test,dc=internal, referer: http://dev.test.internal/wp-login.php
```
/
```typescript
[Fri Sep 15 15:49:28.907624 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] LDAP groups: ["testuser08"], referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 15:49:28.907871 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] Roles from LDAP group: [], referer: http://dev.test.internal/wp-login.php
``` 
```php 
[Fri Sep 15 15:49:28.908025 2023] [php:notice] [pid 38463] [client 10.8.1.178:57482] [AuthLDAP] user is not in any group that is allowed access, referer: http://dev.test.internal/wp-login.php
```

Looks like that cn does not help enough with this filter. I do not have idea what else should I try to tune... to get this 

Kind regards,
Vlad

**Comment by heiglandreas** [comment]
Ah! My mistake!

The groups are added as `memberOf` to the user!

That then requires the whole `dn` of the group in tue group matching config. So instead of

   Editor: WP-EDITORS-TEST

it needs to be

  Editor: CN=WP-EDITORS-TEST,CN....

**Comment by vnovakovic** [comment]
Works flowless! Thank you a lot Andreas!

just as reference, here is my document of running setup for integration authLDAP with Windows Active Directory if you store users and groups under Windows cn=Users,dc=example,dc=com (in my case cn=Users,dc=test,dc=internal):
 
General Usage of authLDAP
-
``` html
Enable Authentication via LDAP? (yes)
Debug AuthLDAP? (yes)
Do not authenticate existing WordPress-Users (empty/default)
Map LDAP Groups to wordpress Roles? (yes)
``` 

General Server Settings
-
```html 
LDAP URI: ldap://CN=ldapreadonly,CN=Users,DC=test,DC=internal:password@10.8.1.21/dc=test,dc=internal;ldap://CN=ldapreadonly,CN=Users,DC=test,DC=internal:password@10.8.1.22/dc=test,dc=internal
LDAP URI-Separator: ;
StartTLS: (empty/default)
Filter: (userPrincipalName=%s)
```
 
Settings for creating new Users
-
```html
User-Read: (yes)
Name-Attribute: displayName
Second Name Attribute: sn
User-ID Attribute: userPrincipalName
Mail Attribute: userPrincipalName
Web-Attribute: (empty/default)
Default Role: (None (deny access))
``` 

Groups for Roles
-
```html 
LDAP Groups override role of existing users?: (yes)
Group-Base: (empty/defaults)
Group-Attribute: memberOf
Group-Separator: _
Group-Filter: (&(objectClass=user)(userPrincipalName=%s)(memberOf=*)) 
``` 

Role - group mapping
-
``` html
Assign this WordPress-Role	to members of this/these LDAP-Groups

Administrator: cn=WP-ADMINISTRATORS-TEST,CN=Users,DC=test,DC=internal
Editor: cn=WP-EDITORS-TEST,CN=Users,DC=test,DC=internal
Author:	cn=WP-AUTHORS-TEST,CN=Users,DC=test,DC=internal
Contributor: cn=WP-CONTRIBUTORS-TEST,CN=Users,DC=test,DC=internal
Subscriber: cn=WP-SUBSCRIBERS-TEST,CN=Users,DC=test,DC=internal
``` 

and healthy Apache log looks like this:

```php
[Fri Sep 15 16:58:44.025758 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] User 'testuser08@test.internal' logging in, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.025794 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] about to do LDAP authentication, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.025805 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] connect to LDAP server, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.028011 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] LDAP authentication successful, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.028480 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] Existing user, uid = 2, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.028583 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] Array\n(\n    [administrator] => CN=WP-ADMINISTRATORS-TEST,CN=Users,DC=test,DC=internal\n    [editor] => CN=WP-EDITORS-TEST,CN=Users,DC=test,DC=internal\n    [author] => cn=WP-AUTHORS-TEST,CN=Users,DC=test,DC=internal\n    [contributor] => cn=WP-CONTRIBUTORS-TEST,CN=Users,DC=test,DC=internal\n    [subscriber] => cn=WP-SUBSCRIBERS-TEST,CN=Users,DC=test,DC=internal\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.028603 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] Array\n(\n    [administrator] => CN=WP-ADMINISTRATORS-TEST,CN=Users,DC=test,DC=internal\n    [editor] => CN=WP-EDITORS-TEST,CN=Users,DC=test,DC=internal\n    [author] => cn=WP-AUTHORS-TEST,CN=Users,DC=test,DC=internal\n    [contributor] => cn=WP-CONTRIBUTORS-TEST,CN=Users,DC=test,DC=internal\n    [subscriber] => cn=WP-SUBSCRIBERS-TEST,CN=Users,DC=test,DC=internal\n)\n, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.028618 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] Group Filter: "(&(objectClass=user)(userPrincipalName=%s)(memberOf=*))", referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.028691 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] Group Base: , referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.028987 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] LDAP groups: ["CN=WP-EDITORS-TEST,CN=Users,DC=test,DC=internal","CN=Group_1d4448da-e39f-41c9-855b-1b16f81d17c9,OU=o365,DC=test,DC=internal"], referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.029010 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] Roles from LDAP group: ["editor"], referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.029019 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] role from group mapping: ["editor"], referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.029114 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] The LDAP user has an entry in the WP-Database, referer: http://dev.test.internal/wp-login.php
[Fri Sep 15 16:58:44.034920 2023] [php:notice] [pid 36836] [client 10.8.1.178:63211] [AuthLDAP] user id = 2, referer: http://dev.test.internal/wp-login.php
```
Kind regards!
Vlad

Gruß aus DUS!

**Comment by heiglandreas** [comment]
Great! Thanks for the feedback!

I'll mark this as documentation so that others can perhaps use this as a template for their setup!
